# Generated by Django 2.1 on 2018-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('campaign_notes', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('session_notes', models.TextField()),
                ('current_objective', models.CharField(max_length=280)),
                ('campaign', models.ForeignKey(on_delete='SET_NULL', to='campaign_manager.Campaign')),
            ],
        ),
    ]
