# Generated by Django 2.1 on 2018-08-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0002_auto_20180802_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='completed_date',
            field=models.DateField(blank=True),
        ),
    ]
