# Generated by Django 2.1 on 2018-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0004_auto_20180802_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default="<class 'datetime.date'>", max_length=200),
        ),
    ]
