# Generated by Django 2.1 on 2018-08-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0005_session_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-03', max_length=200),
        ),
    ]
