# Generated by Django 2.1 on 2018-08-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0008_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-06', max_length=200),
        ),
    ]
