# Generated by Django 2.1 on 2018-08-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0009_auto_20180806_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.TextField()),
                ('rewards', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hit_points', models.IntegerField()),
                ('reference_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='monsters',
            field=models.ManyToManyField(to='campaign_manager.Monster'),
        ),
    ]
