# Generated by Django 2.1 on 2018-08-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0010_auto_20180806_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='campaign_manager.Session'),
            preserve_default=False,
        ),
    ]
