# Generated by Django 2.1 on 2018-08-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0011_encounter_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='monsters',
        ),
        migrations.AddField(
            model_name='encounter',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Monster',
        ),
    ]
