# Generated by Django 2.1 on 2018-08-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0012_auto_20180806_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hit_points', models.IntegerField()),
                ('url', models.URLField()),
                ('encounters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaign_manager.Encounter')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-05', max_length=200),
        ),
    ]
