# Generated by Django 2.1 on 2018-08-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0013_auto_20180805_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='skipped',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-06', max_length=200),
        ),
    ]
