# Generated by Django 2.1 on 2018-08-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0014_auto_20180806_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-07', max_length=200),
        ),
    ]
