# Generated by Django 2.1 on 2018-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0015_auto_20180807_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='2018-08-09', max_length=200),
        ),
    ]
