# Generated by Django 2.1 on 2018-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0016_auto_20180809_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_name',
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('combat', 'combat'), ('dialog', 'dialog'), ('random', 'random')], default='combat', max_length=34),
        ),
        migrations.AddField(
            model_name='session',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='2018-08-23', max_length=200),
        ),
    ]
